-- =====================================================
-- RESEARCH AGENT v6.1 ARCHITECTURE
-- Three-layer system:
--   Layer 1: Research (AI-generated markdown report)
--   Layer 2: Extraction (Structured data from research)
--   Layer 3: Strategy (Sales approach from extracted data)
-- =====================================================

-- =====================================================
-- LAYER 1: COMPANY RESEARCH
-- Stores the full markdown research report generated by v6.1 agent
-- This is the "Company Research" tab content
-- =====================================================

CREATE TABLE IF NOT EXISTS company_research (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,

  -- The main deliverable: comprehensive markdown report
  markdown_report TEXT NOT NULL,

  -- Research metadata
  version TEXT NOT NULL DEFAULT '6.1',
  researched_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duration_seconds INTEGER,
  tool_calls INTEGER,
  phases_completed TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- Confidence
  confidence_score INTEGER CHECK (confidence_score >= 0 AND confidence_score <= 100),
  confidence_breakdown JSONB DEFAULT '{}'::jsonb,

  -- Key findings for quick reference
  key_findings TEXT[] DEFAULT ARRAY[]::TEXT[],
  summary TEXT,

  -- Canonical identity snapshot
  canonical_identity JSONB DEFAULT '{}'::jsonb,

  -- Raw findings (for extraction layer)
  findings JSONB DEFAULT '{}'::jsonb,
  inferences JSONB DEFAULT '{}'::jsonb,
  tech_stack JSONB DEFAULT '[]'::jsonb,
  growth_signals JSONB DEFAULT '[]'::jsonb,
  timeline JSONB DEFAULT '[]'::jsonb,
  gaps JSONB DEFAULT '[]'::jsonb,
  discrepancies JSONB DEFAULT '[]'::jsonb,

  -- Status
  status TEXT DEFAULT 'completed' CHECK (status IN ('pending', 'researching', 'completed', 'failed', 'stale')),
  error_message TEXT,

  -- Audit
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id),

  UNIQUE(company_id)
);

-- =====================================================
-- LAYER 2: COMPANY EXTRACTIONS
-- Structured data extracted from research report
-- User can review and edit before generating strategy
-- =====================================================

CREATE TABLE IF NOT EXISTS company_extractions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  research_id UUID REFERENCES company_research(id) ON DELETE SET NULL,

  -- =====================
  -- IDENTITY (extracted)
  -- =====================
  company_name TEXT,
  legal_entity TEXT,
  domain TEXT,
  hq_city TEXT,
  hq_state TEXT,

  -- =====================
  -- OWNERSHIP (extracted)
  -- =====================
  ownership_type TEXT CHECK (ownership_type IN ('family', 'pe_backed', 'franchise', 'independent', 'unknown')),
  family_generation TEXT,
  pe_firm TEXT,
  franchise_brand TEXT,
  owner_name TEXT,
  owner_title TEXT,

  -- =====================
  -- SIZE (extracted)
  -- =====================
  employee_count INTEGER,
  employee_count_range TEXT,
  location_count INTEGER,
  states_served TEXT[] DEFAULT ARRAY[]::TEXT[],
  revenue BIGINT,
  revenue_year INTEGER,

  -- =====================
  -- REPUTATION (extracted)
  -- =====================
  founded_year INTEGER,
  years_in_business INTEGER,
  bbb_rating TEXT,
  google_rating DECIMAL(2,1),
  google_review_count INTEGER,

  -- =====================
  -- INDUSTRY POSITION (extracted)
  -- =====================
  pct_rank INTEGER,
  pct_rank_year INTEGER,
  industry_awards JSONB DEFAULT '[]'::jsonb,
  association_memberships JSONB DEFAULT '[]'::jsonb,

  -- =====================
  -- TECHNOLOGY (extracted)
  -- =====================
  fsm_vendor TEXT,
  fsm_confidence TEXT,
  tech_stack JSONB DEFAULT '[]'::jsonb,
  has_customer_portal BOOLEAN,
  portal_url TEXT,

  -- =====================
  -- GROWTH SIGNALS (extracted)
  -- =====================
  hiring_activity TEXT CHECK (hiring_activity IN ('none', 'low', 'moderate', 'high', 'very_high')),
  recent_acquisitions JSONB DEFAULT '[]'::jsonb,
  geographic_expansion BOOLEAN,
  service_line_expansion BOOLEAN,

  -- =====================
  -- LEADERSHIP TEAM (extracted)
  -- Array of { name, title, email, linkedin, is_decision_maker }
  -- =====================
  leadership_team JSONB DEFAULT '[]'::jsonb,

  -- =====================
  -- TIMELINE (extracted)
  -- =====================
  company_timeline JSONB DEFAULT '[]'::jsonb,

  -- =====================
  -- USER EDITS
  -- =====================
  user_edits JSONB DEFAULT '{}'::jsonb, -- Track which fields user modified
  edited_at TIMESTAMP WITH TIME ZONE,
  edited_by UUID REFERENCES auth.users(id),

  -- Status
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'extracted', 'reviewed', 'approved')),
  extraction_confidence INTEGER,

  -- Audit
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(company_id)
);

-- =====================================================
-- LAYER 3: COMPANY STRATEGIES
-- Sales strategy generated from extracted data
-- =====================================================

CREATE TABLE IF NOT EXISTS company_strategies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES companies(id) ON DELETE CASCADE,
  extraction_id UUID REFERENCES company_extractions(id) ON DELETE SET NULL,

  -- =====================
  -- POSITIONING
  -- =====================
  primary_positioning TEXT,
  positioning_emoji TEXT,
  secondary_positioning TEXT[] DEFAULT ARRAY[]::TEXT[],
  classification_tags TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- WHY THEY BUY
  -- =====================
  pain_points TEXT[] DEFAULT ARRAY[]::TEXT[],
  desired_outcomes TEXT[] DEFAULT ARRAY[]::TEXT[],
  buying_triggers TEXT[] DEFAULT ARRAY[]::TEXT[],
  why_they_buy_summary TEXT,

  -- =====================
  -- SALES APPROACH
  -- =====================
  recommended_approach TEXT,
  entry_point TEXT,
  best_timing TEXT,
  target_roles TEXT[] DEFAULT ARRAY[]::TEXT[],
  decision_makers TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- TALKING POINTS
  -- Array of { point, data_reference, priority }
  -- =====================
  talking_points JSONB DEFAULT '[]'::jsonb,
  key_messages TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- OBJECTIONS
  -- Array of { objection, response, likelihood }
  -- =====================
  likely_objections JSONB DEFAULT '[]'::jsonb,

  -- =====================
  -- QUESTIONS TO ASK
  -- =====================
  discovery_questions TEXT[] DEFAULT ARRAY[]::TEXT[],
  qualifying_questions TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- THINGS TO AVOID
  -- =====================
  things_to_avoid TEXT[] DEFAULT ARRAY[]::TEXT[],
  sensitive_topics TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- CALL PREP
  -- =====================
  call_prep_checklist TEXT[] DEFAULT ARRAY[]::TEXT[],
  conversation_starters TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- COMPETITIVE INTEL
  -- =====================
  incumbent_vendor TEXT,
  competitive_angle TEXT,
  differentiation_points TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- =====================
  -- FULL REPORT
  -- =====================
  full_report_markdown TEXT,

  -- =====================
  -- GENERATION METADATA
  -- =====================
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  generated_by UUID REFERENCES auth.users(id),
  generation_model TEXT DEFAULT 'claude-sonnet-4-20250514',
  data_snapshot JSONB, -- Snapshot of extraction data used

  -- Status
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'generating', 'generated', 'reviewed', 'approved')),

  -- Audit
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  UNIQUE(company_id)
);

-- =====================================================
-- RESEARCH METHODOLOGY CONFIGURATION
-- Configurable parameters for research agent
-- =====================================================

CREATE TABLE IF NOT EXISTS research_methodology (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  is_default BOOLEAN DEFAULT FALSE,

  -- Phase configuration
  phases JSONB DEFAULT '["identify", "ground", "enrich", "validate"]'::jsonb,

  -- Tool limits
  max_tool_calls INTEGER DEFAULT 45,
  timeout_seconds INTEGER DEFAULT 300,

  -- Source priorities (higher = preferred)
  source_priorities JSONB DEFAULT '{
    "bbb": 90,
    "pct_top_100": 95,
    "business_journals": 85,
    "linkedin": 70,
    "google_places": 75,
    "company_website": 80,
    "apollo": 50
  }'::jsonb,

  -- Industry knowledge base version
  industry_kb_version TEXT DEFAULT '2024.1',

  -- Custom prompts
  custom_system_prompt TEXT,

  -- Audit
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id)
);

-- Insert default methodology
INSERT INTO research_methodology (name, description, is_default) VALUES
('Standard v6.1', 'Default 4-phase research protocol with 45 tool call limit', TRUE);

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_company_research_company_id ON company_research(company_id);
CREATE INDEX IF NOT EXISTS idx_company_research_status ON company_research(status);
CREATE INDEX IF NOT EXISTS idx_company_research_researched_at ON company_research(researched_at);
CREATE INDEX IF NOT EXISTS idx_company_research_confidence ON company_research(confidence_score);

CREATE INDEX IF NOT EXISTS idx_company_extractions_company_id ON company_extractions(company_id);
CREATE INDEX IF NOT EXISTS idx_company_extractions_research_id ON company_extractions(research_id);
CREATE INDEX IF NOT EXISTS idx_company_extractions_status ON company_extractions(status);
CREATE INDEX IF NOT EXISTS idx_company_extractions_ownership ON company_extractions(ownership_type);

CREATE INDEX IF NOT EXISTS idx_company_strategies_company_id ON company_strategies(company_id);
CREATE INDEX IF NOT EXISTS idx_company_strategies_extraction_id ON company_strategies(extraction_id);
CREATE INDEX IF NOT EXISTS idx_company_strategies_status ON company_strategies(status);

-- =====================================================
-- ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE company_research ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE research_methodology ENABLE ROW LEVEL SECURITY;

-- Policies for company_research
CREATE POLICY "Users can view company research" ON company_research
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert company research" ON company_research
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can update company research" ON company_research
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Users can delete company research" ON company_research
  FOR DELETE TO authenticated USING (true);

-- Policies for company_extractions
CREATE POLICY "Users can view extractions" ON company_extractions
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert extractions" ON company_extractions
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can update extractions" ON company_extractions
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Users can delete extractions" ON company_extractions
  FOR DELETE TO authenticated USING (true);

-- Policies for company_strategies
CREATE POLICY "Users can view strategies" ON company_strategies
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert strategies" ON company_strategies
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can update strategies" ON company_strategies
  FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Users can delete strategies" ON company_strategies
  FOR DELETE TO authenticated USING (true);

-- Policies for research_methodology
CREATE POLICY "Users can view methodologies" ON research_methodology
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can insert methodologies" ON research_methodology
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Users can update methodologies" ON research_methodology
  FOR UPDATE TO authenticated USING (true);

-- =====================================================
-- TRIGGERS
-- =====================================================

-- Update timestamp triggers
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_company_research_updated_at
  BEFORE UPDATE ON company_research
  FOR EACH ROW
  EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trigger_company_extractions_updated_at
  BEFORE UPDATE ON company_extractions
  FOR EACH ROW
  EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trigger_company_strategies_updated_at
  BEFORE UPDATE ON company_strategies
  FOR EACH ROW
  EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trigger_research_methodology_updated_at
  BEFORE UPDATE ON research_methodology
  FOR EACH ROW
  EXECUTE FUNCTION update_timestamp();

-- =====================================================
-- HELPER FUNCTIONS
-- =====================================================

-- Function to get the latest research for a company
CREATE OR REPLACE FUNCTION get_company_research(p_company_id UUID)
RETURNS company_research AS $$
BEGIN
  RETURN (
    SELECT *
    FROM company_research
    WHERE company_id = p_company_id
    ORDER BY researched_at DESC
    LIMIT 1
  );
END;
$$ LANGUAGE plpgsql;

-- Function to check if research is stale (>30 days old)
CREATE OR REPLACE FUNCTION is_research_stale(p_company_id UUID, p_days INTEGER DEFAULT 30)
RETURNS BOOLEAN AS $$
DECLARE
  last_researched TIMESTAMP WITH TIME ZONE;
BEGIN
  SELECT researched_at INTO last_researched
  FROM company_research
  WHERE company_id = p_company_id
  ORDER BY researched_at DESC
  LIMIT 1;

  IF last_researched IS NULL THEN
    RETURN TRUE;
  END IF;

  RETURN last_researched < NOW() - (p_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Function to get intelligence status for a company
CREATE OR REPLACE FUNCTION get_intelligence_status(p_company_id UUID)
RETURNS TABLE (
  has_research BOOLEAN,
  has_extraction BOOLEAN,
  has_strategy BOOLEAN,
  research_status TEXT,
  extraction_status TEXT,
  strategy_status TEXT,
  research_confidence INTEGER,
  is_stale BOOLEAN
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    EXISTS(SELECT 1 FROM company_research WHERE company_id = p_company_id) as has_research,
    EXISTS(SELECT 1 FROM company_extractions WHERE company_id = p_company_id) as has_extraction,
    EXISTS(SELECT 1 FROM company_strategies WHERE company_id = p_company_id) as has_strategy,
    COALESCE((SELECT cr.status FROM company_research cr WHERE cr.company_id = p_company_id), 'none') as research_status,
    COALESCE((SELECT ce.status FROM company_extractions ce WHERE ce.company_id = p_company_id), 'none') as extraction_status,
    COALESCE((SELECT cs.status FROM company_strategies cs WHERE cs.company_id = p_company_id), 'none') as strategy_status,
    COALESCE((SELECT cr.confidence_score FROM company_research cr WHERE cr.company_id = p_company_id), 0) as research_confidence,
    is_research_stale(p_company_id) as is_stale;
END;
$$ LANGUAGE plpgsql;
